name       : nitrokey-app
version    : 1.4.2
release    : 2
source     :
    - https://github.com/Nitrokey/nitrokey-app/releases/download/v1.4.2/nitrokey-app-v1.4.2.tar.gz : 965c05409c0fb534b8092eb66a54bafd4cb1a2e50f15cf197f6527ae14747634
license    : GPL-3.0-or-later
component  : security
summary    : Nitrokey App is a cross-platform application created to manage Nitrokey devices.
description: |
    Nitrokey App is a cross-platform (runs under Windows, Linux and Mac OS) application created to manage Nitrokey devices. Underneath it uses libnitrokey to communicate with the supported devices.
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libnitrokey-1)
    - cppcodec
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/icons/ubuntu-mono-dark
    rm -rf $installdir/usr/share/icons/ubuntu-mono-light