name       : nitrokey-app
version    : 1.3.2
release    : 1
source     :
    - https://github.com/Nitrokey/nitrokey-app/releases/download/v1.3.2/nitrokey-app-v1.3.2.tar.gz : 21296fcbdee244d7de3960c04ca555f056352c75accbde909a8019ee96a146e3
license    : GPL-3.0-or-later
component  : security
summary    : Nitrokey App is a cross-platform application created to manage Nitrokey devices. 
description: |
    Nitrokey App is a cross-platform (runs under Windows, Linux and Mac OS) application created to manage Nitrokey devices. Underneath it uses libnitrokey to communicate with the supported devices.
builddeps  : 
    - pkgconfig(bash-completion)
    - pkgconfig(cppcodec-1)
    - pkgconfig(libnitrokey-1)
    - pkgconfig(Qt5Concurrent)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - hicolor-icon-theme
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/icons/ubuntu-mono-dark
    rm -rf $installdir/usr/share/icons/ubuntu-mono-light